SELECT TOP 10 * FROM [dbo].[product_category_name_translation] ------ TABELA MAE

create table TB_ACT_OLIST_PRODUCT_NAME
(
PRODUCT_CATEGORY_NAME VARCHAR(100),
PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(100)
)

INSERT INTO TB_ACT_OLIST_PRODUCT_NAME ---------- INSERE NA TABELA NOVA, OS VALORES DA TABELA MÃE
SELECT * FROM [dbo].[product_category_name_translation]

SELECT * FROM TB_ACT_OLIST_PRODUCT_NAME

UPDATE [dbo].[TB_ACT_OLIST_ORDERS] SET [ORDER_ESTIMATED_DELIVERY_DATE] = NULL
WHERE [ORDER_ESTIMATED_DELIVERY_DATE] = '' ------------ TIRA OS CAMPOS EM BRANCOS

SELECT * FROM [dbo].[TB_ACT_OLIST_ORDERS]

