SELECT * FROM [dbo].[dbo].[TB_ACT_OLIST_CUSTOMER]

CREATE VIEW VW_PEDIDOS_POR_CLIENTE
AS
SELECT O.*, C.CUSTOMER_CITY, C.CUSTOMER_STATE
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [TB_ACT_OLIST_CUSTOMER] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID 

ALTER VIEW VW_PEDIDOS_POR_CLIENTE
AS
SELECT O.*, C.CUSTOMER_CITY, C.CUSTOMER_STATE
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [TB_ACT_OLIST_CUSTOMER] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID WHERE ORDER_STATUS = 'delivered'


SELECT * FROM VW_PEDIDOS_POR_CLIENTE